apiVersion: v1
kind: Service
metadata:
  name: flask-hello-nodeport
spec:
  type: NodePort
  selector:
    app: flask-hello
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # Optional, else auto-assigned
